spring:
  application:
    name: backend
  profiles:
    default: dev
  datasource:
    url: "${DB_URL}"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: "${REDIS_HOST}"
      port: "${REDIS_PORT}"
      password: "${REDIS_PASSWORD}"
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:false}
    locations: classpath:db/migration

ai:
  gemini:
    api-key: ${GMS_KEY}
    model: ${GEMINI_MODEL:gemini-2.5-flash-lite}
    base-url: ${GEMINI_BASE_URL:https://gms.ssafy.io/gmsapi/generativelanguage.googleapis.com}

  clova:
    client-id: ${CLOVA_CLIENT_ID}
    client-secret: ${CLOVA_CLIENT_SECRET}

    tts-url: ${CLOVA_TTS_URL:https://naveropenapi.apigw.ntruss.com/tts-premium/v1/tts}
    speaker: ${CLOVA_TTS_SPEAKER:nara}
    format: ${CLOVA_TTS_FORMAT:mp3}

    stt-url: ${CLOVA_STT_URL:https://naveropenapi.apigw.ntruss.com/recog/v1/stt}
    stt-language: ${CLOVA_STT_LANGUAGE:Kor}

external-api:
  timeout:
    connect: 3s
    read: 10s

sign-ai:
  base-url: ${SIGN_AI_BASE_URL:http://localhost:8000}
  timeout:
    connect: ${SIGN_AI_CONNECT_TIMEOUT:1s}
    read: ${SIGN_AI_READ_TIMEOUT:1s}

app:
  asset:
    cloud-front-domain: ${ASSET_CLOUDFRONT_DOMAIN:https://d14zyw67949hvk.cloudfront.net}

